<style>
.footer {
    padding: 30px 0 15px;
    background: #ddd;
    color: #333;
    text-align: center;
    font-size: 16px;
    line-height: 24px;
    font-weight: bold;
}
.footer a {
    color: #dc7b27;
}
</style>

<div class="footer">
	<div>Content Provided by: Inspector General of Registration and Superintendent of Stamp, Govt. of Chhattishgarh</div>
	<div>Site Designed and Developed by IT Solution | <a href="http://www.itsolutionindia.org/" target="_blank">www.itsolutionindia.org</a></div>
	<div>Help Line No. :- 0771 491 2523 / 1800 233 2488 | Email Id :- techsupport@itsolutionindia.com</div>
</div>